# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a810d8e27988a2b5afc7a8047409294720d29f7710a9ed1c41a72e45368ffcfc4f5501a2f0ef4dc886c719975a3bade2e40a70dd5e36e0294b5dccf9c5e37ad1

test:
  secret_key_base: 63b004f09384c2bc1afff6943805c8be8ec0a6803fee00215a4bc87c9bbafbd5e0880722e8560e0723a027e3631e7716e2acde335884816fdc5868281bd63c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
